all:
	(cd timerLib && make install)
	(cd alternatelights && make)
	(cd playbuzzer && make)

clean:
	(cd timerLib && make clean)
	(cd alternatelights && make clean)
	(cd playbuzzer && make clean)
	rm -rf *~
